### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by volodymyr-kushnir** [katesemyroz/Hometask_for_Binary_Studio#1]
@katesemyroz so far so good, keep it up.
Could you also add a **README.md** with a short description of your project, please?

P. S. Also take a look on some [**Lifehacks and hints**](https://github.com/volodymyr-kushnir/agenda), perhaps something could be useful.

**Comment by katesemyroz** [comment]
@volodymyr-kushnir,
Thanks a lot for reviewing my repository. 
README.md was successfully added.
